### ISSUE TITLE
align problem with superscript characters (cm²)

### ISSUE THREAD

**Issue by Noxigar** [seleznevae/libfort#16]
Hello, 

With cm² and cm³ text in tables are not properly aligned.
This happens both on headers and cells values
[https://pastebin.com/Q4frZq45](url)

**Comment by seleznevae** [comment]
Superscripts and subscripts are not ASCII symbols. For correct behavior to show UTF-8 text, you should use UTF-8 API (it was added several weeks ago). 
Here is a simple example:
```c
#ifdef FT_HAVE_UTF8
    ft_table_t *table = ft_create_table();
    ft_set_border_style(table, FT_DOUBLE2_STYLE);
    ft_set_cell_prop(table, 0, FT_ANY_COLUMN, FT_CPROP_ROW_TYPE, FT_ROW_HEADER);

    ft_u8write_ln(table, "N", "Figure", "Volume, cm³", "Accuracy");

    ft_u8write_ln(table, "1", "○", "3.145", "±0.3");
    ft_u8write_ln(table, "2", "◸", "4.95", "±0.25");

    printf("%s\n", (const char *)ft_to_u8string(table));
    ft_destroy_table(table);
#endif /* FT_HAVE_UTF8 */
```
Output in my terminal:
![image](https://user-images.githubusercontent.com/16498414/65067700-c890e300-d98f-11e9-9678-8b95fee55abb.png)

Did you use UTF-8 API (`ft_u8printf`, `ft_u8write`) or methods for ascii texts(`ft_printf`, `ft_write`...)?

**Comment by Noxigar** [comment]
Thanks for the reply.
I'm using the C++ API not the C one, so I think I'm using the methods for ASCII texts.
I'll switch to the UTF-8 C API and test again.

**Comment by Noxigar** [comment]
It's ok with the UTF-8 API, thanks a lot.
