### ISSUE TITLE
something wrong about decoding chars in windows shell

### ISSUE THREAD

**Issue by ltg001** [seleznevae/libfort#2]
Hello,
I followed the instruction in README.md
But I get something wrong using `FT_DOUBLE2_STYLE`.
In windows like bash (cmd and powershell), I got something like this.
![image](https://user-images.githubusercontent.com/14017336/57123342-05c75080-6db4-11e9-884d-5bed99533632.png)
But when I use Unix like bash (git bash) it went right.
![image](https://user-images.githubusercontent.com/14017336/57123380-27283c80-6db4-11e9-823d-90b9189121cd.png)

I use clang v8.0.0 and msvc 2017 for compiling.
Thanks for the lib, it helped me a lot.

**Comment by seleznevae** [comment]
Hello,
not very sure about the cause of the problem since I am not a Windows user myself. Let's try to find out.

`FT_DOUBLE2_STYLE` border characters are not the part of ASCII.
Could you please, try to output this border characters in your windows console without using the library. Something like this:
```
int main()
{
    printf("╔");  // replace `printf` with something that you use in your application
    printf("╗");
}
```
By the way did you use *char* or *wchar_t*?

**Comment by ltg001** [comment]
Sorry for late reply.
I tried the code and it failed.
![image](https://user-images.githubusercontent.com/14017336/57211388-a6b34700-7012-11e9-99c0-54d14f6c8728.png)
I got this 
![image](https://user-images.githubusercontent.com/14017336/57211400-b763bd00-7012-11e9-985d-c08feac19e10.png)

I did not use `char` or `wchar_t` in my code.

**Comment by seleznevae** [comment]
It seems like some console problems and not a `libfort` library issue (library just give you some string representation and how this string is shown in the console is out of library scope).
 You should find how to  deal with these problems with your console. Maybe internet will help you (https://stackoverflow.com/questions/1371012/how-do-i-print-utf-8-from-c-console-application-on-windows or something else). 
At the moment you are using `char`. If in the end you won't be able to show border properly you can also try using `wchar_t`:
```
#include <iostream>

int main()
{
    std::wcout << L"Hello, world!\n";
    std::wcout << L"╔\n";
}
```

**Comment by ltg001** [comment]
It perfectly solved my problem!
Thanks you very much!
Thanks again for the great lib.
