### ISSUE TITLE
undefined reference to `ft_create_table'

### ISSUE THREAD

**Issue by electrodragon** [seleznevae/libfort#35]
Any Fix?

[atta@atta-pc APP]$ g++ app.cpp -std=c++11
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>::table()':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EEC2Ev[_ZN4fort5tableILNS_10table_typeE0EEC5Ev]+0x33): undefined reference to `ft_create_table'
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>::~table()':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EED2Ev[_ZN4fort5tableILNS_10table_typeE0EED5Ev]+0x18): undefined reference to `ft_destroy_table'
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>::operator<<(fort::table_manipulator const&)':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsERKNS_17table_manipulatorE[_ZN4fort5tableILNS_10table_typeE0EElsERKNS_17table_manipulatorE]+0x41): undefined reference to `ft_set_cell_prop'
/usr/bin/ld: app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsERKNS_17table_manipulatorE[_ZN4fort5tableILNS_10table_typeE0EElsERKNS_17table_manipulatorE]+0x63): undefined reference to `ft_ln'
/usr/bin/ld: app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsERKNS_17table_manipulatorE[_ZN4fort5tableILNS_10table_typeE0EElsERKNS_17table_manipulatorE]+0x85): undefined reference to `ft_add_separator'
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>& fort::table<(fort::table_type)0>::operator<< <char [2]>(char const (&) [2])':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsIA2_cEERS2_RKT_[_ZN4fort5tableILNS_10table_typeE0EElsIA2_cEERS2_RKT_]+0xa2): undefined reference to `ft_nwrite'
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>& fort::table<(fort::table_type)0>::operator<< <char [7]>(char const (&) [7])':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsIA7_cEERS2_RKT_[_ZN4fort5tableILNS_10table_typeE0EElsIA7_cEERS2_RKT_]+0xa2): undefined reference to `ft_nwrite'
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>& fort::table<(fort::table_type)0>::operator<< <char [5]>(char const (&) [5])':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsIA5_cEERS2_RKT_[_ZN4fort5tableILNS_10table_typeE0EElsIA5_cEERS2_RKT_]+0xa2): undefined reference to `ft_nwrite'
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>& fort::table<(fort::table_type)0>::operator<< <char [10]>(char const (&) [10])':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsIA10_cEERS2_RKT_[_ZN4fort5tableILNS_10table_typeE0EElsIA10_cEERS2_RKT_]+0xa2): undefined reference to `ft_nwrite'
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>& fort::table<(fort::table_type)0>::operator<< <char [9]>(char const (&) [9])':
app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsIA9_cEERS2_RKT_[_ZN4fort5tableILNS_10table_typeE0EElsIA9_cEERS2_RKT_]+0xa2): undefined reference to `ft_nwrite'
/usr/bin/ld: /tmp/ccgEbx1a.o:app.cpp:(.text._ZN4fort5tableILNS_10table_typeE0EElsIA6_cEERS2_RKT_[_ZN4fort5tableILNS_10table_typeE0EElsIA6_cEERS2_RKT_]+0xa2): more undefined references to `ft_nwrite' follow
/usr/bin/ld: /tmp/ccgEbx1a.o: in function `fort::table<(fort::table_type)0>::c_str() const':
app.cpp:(.text._ZNK4fort5tableILNS_10table_typeE0EE5c_strEv[_ZNK4fort5tableILNS_10table_typeE0EE5c_strEv]+0x18): undefined reference to `ft_to_string'
collect2: error: ld returned 1 exit status

**Comment by seleznevae** [comment]
Since you are using g++ (compiler for c++) I understand that you use `fort.hpp`.
`fort.hpp` simply contains useful wrappers around the library c library. Therefore you have to compile also library itself. In your case it should be something like:
```
g++ app.cpp PATH_TO_LIBFORT/lib/fort.c -std=c++11
```

**Comment by electrodragon** [comment]
Thanks It Worked !

**Comment by seleznevae** [comment]
Resolving.
