### ISSUE TITLE
No CMake option to disable unit test

### ISSUE THREAD

**Issue by neel** [seleznevae/libfort#44]
Please add CMake option to disable unit tests and examples for this sub project only.

**Comment by seleznevae** [comment]
Added cmake option `FORT_ENABLE_TESTING` to turn on/off tests and examples.
By default `FORT_ENABLE_TESTING` is `ON`.
Changes are merged to `develop` branch.

**Comment by seleznevae** [comment]
Resolving issue for now. If any suggestions or something is incorrect, please reopen.
