### ISSUE TITLE
How to set decimal precision in a column?

### ISSUE THREAD

**Issue by diegopaiva1** [seleznevae/libfort#49]
First, thanks for this great lib. I'm filling a table with data from a `double` array. However, I can't manage to print the table with exactly two digits after decimal point without generating extra columns.

 Here's the code to generate the table:

```cpp
double data[3][3] = {
  {3.4403, 5.1802, 0.0071},
  {18.931, 22.004, 0.0000},
  {  74.5, 100.01, 9.1110}
};

fort::char_table t1;

t1 << fort::header << "#" << "arrival time" << "departure time" << "waiting time" << fort::endr;

t1.column(0).set_cell_text_align(fort::text_align::center);
t1.column(1).set_cell_text_align(fort::text_align::right);
t1.column(2).set_cell_text_align(fort::text_align::right);
t1.column(3).set_cell_text_align(fort::text_align::right);

// Fill with data
for (int i = 0; i < 3; i++) {
  t1 << i;
  for (int j = 0; j < 3; j++)
    t1 << data[i][j];

  t1 << fort::endr;
}

std::cout << t1.to_string() << std::endl;
```

Output:

```
+---+--------------+----------------+--------------+
| # | arrival time | departure time | waiting time |
+---+--------------+----------------+--------------+
| 0 |       3.4403 |         5.1802 |       0.0071 |
| 1 |       18.931 |         22.004 |            0 |
| 2 |         74.5 |         100.01 |        9.111 |
+---+--------------+----------------+--------------+
```

I tried using `std::setprecision` and `std::fixed` from `<iomanip>` to print every cell with two digits after decimal point, but it did not work. 

My attempts:

1.   Adding `std::cout << std::fixed << std::setprecision(2);` before the line `std::cout << t1.to_string() << std::endl;`. Output is the same as before.

2.  Replacing `t1 << data[i][j];` by `t1 << std::fixed << std::setprecision(2) << data[i][j];`. Output:

```
+---+--------------+----------------+--------------+--+--+--------+--+--+------+
| # | arrival time | departure time | waiting time |  |  |        |  |  |      |
+---+--------------+----------------+--------------+--+--+--------+--+--+------+
| 0 |              |                |         3.44 |  |  | 5.18   |  |  | 0.01 |
| 1 |              |                |        18.93 |  |  | 22.00  |  |  | 0.00 |
| 2 |              |                |        74.50 |  |  | 100.01 |  |  | 9.11 |
+---+--------------+----------------+--------------+--+--+--------+--+--+------+
```

As you can see, it actually prints the values as expected, but it generates empty columns and disarranges the table.

3.   Adding `t1 << std::fixed << std::setprecision(2);` before the first `for` loop. Output has issues similar to 2nd attempt:

```
+---+--------------+----------------+--------------+------+------+
| # | arrival time | departure time | waiting time |      |      |
+---+--------------+----------------+--------------+------+------+
|   |              |              0 |         3.44 | 5.18 | 0.01 |
| 1 |        18.93 |          22.00 |         0.00 |      |      |
| 2 |        74.50 |         100.01 |         9.11 |      |      |
+---+--------------+----------------+--------------+------+------+
```

Other attempts also did not produce the expected output. I'm sorry, but I did not find in the tutorials something related to this issue. What am I missing here? Thanks in advance.

**Comment by seleznevae** [comment]
Hi!
That's a bug. Thanks for reporting. I'll try to fix if possible.

**Comment by seleznevae** [comment]
Hi!
That's a bug. Thanks for reporting. I'll try to fix if possible.

**Comment by seleznevae** [comment]
Merged to develop. 
Resolving.
Please reopen if it doesn't work for you.

**Comment by diegopaiva1** [comment]
> Merged to develop.
> Resolving.
> Please reopen if it doesn't work for you.

Worked by adding `t1 << std::fixed << std::setprecision(2)` right after `fort::char_table t1`. Thanks for the fast fix.
