### ISSUE TITLE
Is it possible to update an existing column in the table without redrawing the whole table

### ISSUE THREAD

**Issue by chreniuc** [seleznevae/libfort#52]
Is there a way to print a table and then update a value from a column and then reprint only that column not the whole table, because nothing else changed?

**Comment by seleznevae** [comment]
Hi!
Don't quite understand what you want and what do you mean when you say `reprint`. 
If you want to change content of the cells for already filled `table` object. It is possible. You should change current cell to the desired cell with `ft_set_cur_cell` and then put their new data. After that to get string representation of the updated table you'll need to call `to_string` of `ft_to_string` and you'll get new string.
If I misunderstood you, please add some description of your use case.

**Comment by chreniuc** [comment]
I just realized that my question is a little bit stupid, because this library only generates a string, it's not a graphical library that can detect the regions that were modified and redraws them.

Let me just tell you anyways.

We are printing a table like this:

```c++
int main()
{
   fort::char_table table;

    table.set_border_style(FT_DOUBLE2_STYLE);

    table.row(0).set_cell_row_type(fort::row_type::header);
    table.write_ln("Col 1", "Col 2");
    table.row(0).set_cell_bg_color(fort::color::light_gray);
    table.row(0).set_cell_content_fg_color(fort::color::black);
    table.row(0).set_cell_content_text_style(fort::text_style::bold);
    table.row(0).set_cell_text_align(fort::text_align::center);

    // fill table:
    table[1][0] = "1";
    table[1][1] = "1111";
    table[2][0] = "2";
    table[2][1] = "2222";

    cout << table.to_string() << std::endl;

    // Live update the existing table that is printed on the console
    table[2][1] = "3333";


    cout << table.to_string() << std::endl;

    return 0;
}
```

And that code reprints that table twice:

```c++
╔═══════╤═══════╗
║ Col 1 │ Col 2 ║
╠═══════╪═══════╣
║ 1     │ 1111  ║
╟───────┼───────╢
║ 2     │ 2222  ║
╚═══════╧═══════╝

╔═══════╤═══════╗
║ Col 1 │ Col 2 ║
╠═══════╪═══════╣
║ 1     │ 1111  ║
╟───────┼───────╢
║ 2     │ 3333  ║
╚═══════╧═══════╝
```

What we wanted was, some mechanism that will update the first table that was printed, and would update/redraw only the column that was modified. I know that we can clear the screen and then reprint everything, but this is expensive and we wanted to avoid this.

Again, after re-reading what I've written in the first post, I realized that this is not a graphical library. Sorry for wasting your time. You can close this issue. Thanks.
