### ISSUE TITLE
Invalid type cast

### ISSUE THREAD

**Issue by ExcpOccured** [seleznevae/libfort#54]
In https://github.com/seleznevae/libfort/blob/ccb892f77dc30c2ebc42916a3f862a965e8c097f/lib/fort.c#L6870 contains a cast from pointer to integer of different size according to CLang warnings 

This may attract side effects for x64 ¯\_(ツ)_/¯

**Comment by seleznevae** [comment]
Hi! Thanks for reporting. I've merged fixes to the `develop` branch.
If it doesn't help in your environment please reopen the issue.
