### ISSUE TITLE
Are unicode characters supported?

### ISSUE THREAD

**Issue by pkbehera** [seleznevae/libfort#62]
I tried the following code on latest libfort code

```
int main() {
    fort::char_table table;
    table << fort::header << "N"
          << "Driver"
          << "Time"
          << "Avg Speed" << fort::endr;
    table << "α"  // unicode!
          << "Hamilton"
          << "1:26.373"
          << "35.02" << fort::endr;
    std::cout << table.to_string() << std::endl;
}
```
Here is the output, **note how the formatting has gone bad!**

```
+----+----------+----------+-----------+
| N  | Driver   | Time     | Avg Speed |
+----+----------+----------+-----------+
| α | Hamilton | 1:26.373 | 35.02     |
+----+----------+----------+-----------+
```
Looks like string length calculations go haywire if we try to put unicode characters in a table.

**Comment by pkbehera** [comment]
Maybe it’s because size calculation of strings with unicode is wrong in libfort. It’s (α) size would be 2 bytes but display/print width is only 1. That is why the alignment is off by 1 white space as seen in the output!!

**Comment by seleznevae** [comment]
Hi! 

`fort::char_table` treats its content as simple one byte chars.

You should use `fort::utf8_table` instead of `fort::char_table`.

Here is a short description about utf8 - https://github.com/seleznevae/libfort#working-with-multibyte-character-strings .

**Comment by pkbehera** [comment]
Thanks
