### ISSUE TITLE
make the header bold?

### ISSUE THREAD

**Issue by pkbehera** [seleznevae/libfort#8]
I need a table with only the header (`row[0]`) in **bold**:
```
fort::table table;
table << fort::header << "A" << "B" << fort::endr;
table << 3.14 << 12345 << fort::endr;
table << 3.14 << 12345 << fort::endr;
table << 3.14 << 12345 << fort::endr;
table.row(0).set_cell_content_text_style(fort::text_style::bold);
table.row(0).set_cell_content_fg_color(fort::color::red);
std::cout << table.to_string() << std::endl;
```
This is making the whole table bold, in fact everything I type in the terminal is bold after running this code. Guess the closing tag for bold text encoding is missing.
However text color for the header row is red as expected.

**Comment by seleznevae** [comment]
Tries on my host machine (ubuntu 17.04, gcc version 6.3.0, GNOME Terminal 3.20.2) ![ex](https://user-images.githubusercontent.com/16498414/61167821-a4a6c080-a54c-11e9-9deb-fbae2bffda4f.png). It works ok.

**Comment by seleznevae** [comment]
Could you, please, provide more information about your environment? Also could output result of table.to_string() to the file, so that we will be able to check all terminal control sequences in the result of `to_string` function?

**Comment by seleznevae** [comment]
Maybe result can depend on the terminal? As you see sequence of terminal control sequences is:
\e[1m -  Enable Bold
\e[31m - Turn on red color
Here goes some text
\e[21m - Reset Bold
\e[39m - Turn on foreground color 
Maybe for you terminal order of sequences must be some other(e.g. \e[21m should be the last one or something like that)?

**Comment by pkbehera** [comment]
I am using Ubuntu 18.04.2 LTS and here is the output
`+------+-------+$
| ^[[1m^[[31mA^[[21m^[[39m    | ^[[1m^[[31mB^[[21m^[[39m     |$
+------+-------+$
| 3.14 | 12345 |$
| 3.14 | 12345 |$
| 3.14 | 12345 |$
+------+-------+$
`

**Comment by seleznevae** [comment]
I don't see anything wrong with your output. There is obviously `\e[21m` (Reset Bold) sequence. What terminal do you use?

**Comment by seleznevae** [comment]
Could you try to output something like this in your terminal:
```bash
echo -e 'Default \e[31m\e[1m BoldAndRed \e[21m OnlyRed \e[39m Default'
```
Here how it looks like in my terminal
![red](https://user-images.githubusercontent.com/16498414/61180959-b27d4400-a627-11e9-904f-7714c6f52ac5.png)

**Comment by seleznevae** [comment]
Tried this on different terminals. On some of them result is weird. Maybe I should't use specific `\e[21m`  (Reset Bold) sequence. It seems that not all terminals may support it. Maybe I should use more general `\e[0m` (Reset all attributes). I'll try to check more terminals and if it turns out that `\e[0m` is more stable 
I'll replace specific `reset` sequences to one generic `\e[0m`.

**Comment by pkbehera** [comment]
> ```shell
> echo -e 'Default \e[31m\e[1m BoldAndRed \e[21m OnlyRed \e[39m Default'
> ```
![image](https://user-images.githubusercontent.com/2176409/61369701-537d3080-a8ae-11e9-8386-90e24d982072.png)

**Comment by pkbehera** [comment]
![image](https://user-images.githubusercontent.com/2176409/61369942-e918c000-a8ae-11e9-91ea-d961147615a8.png)
using generic `\e[0m` seems to work, I guess that what we need?

**Comment by seleznevae** [comment]
Merged fix to `develop` branch. Please check if it solves problem in your environment.

**Comment by pkbehera** [comment]
![image](https://user-images.githubusercontent.com/2176409/61575059-d4257200-aae4-11e9-9235-312a4366e758.png)
Looking great!
